import { appSchema, tableSchema } from "@nozbe/watermelondb"

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: "transactions",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "type", type: "string" },
        { name: "category", type: "string" },
        { name: "date", type: "string", isIndexed: true },
        { name: "source", type: "string" },
        { name: "encrypted_amount", type: "string" },
        { name: "encrypted_description", type: "string" },
        { name: "encrypted_merchant", type: "string", isOptional: true },
        { name: "encrypted_raw_notification", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "broker_accounts",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "broker", type: "string" },
        { name: "encrypted_current_value", type: "string" },
        { name: "encrypted_total_invested", type: "string" },
        { name: "encrypted_returns", type: "string" },
        { name: "encrypted_returns_percent", type: "string" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "investment_transactions",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "broker_account_id", type: "string", isIndexed: true },
        { name: "type", type: "string" },
        { name: "date", type: "string", isIndexed: true },
        { name: "source", type: "string" },
        { name: "encrypted_amount", type: "string" },
        { name: "encrypted_note", type: "string", isOptional: true },
        { name: "encrypted_raw_notification", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "goals",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "title", type: "string" },
        { name: "type", type: "string" },
        { name: "priority", type: "number" },
        { name: "deadline", type: "string", isOptional: true },
        { name: "is_active", type: "boolean" },
        { name: "deducts_from_networth", type: "boolean" },
        { name: "encrypted_target_amount", type: "string" },
        { name: "encrypted_current_amount", type: "string" },
        { name: "encrypted_description", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "notification_patterns",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "broker_or_bank", type: "string" },
        { name: "is_template", type: "boolean" },
        { name: "extraction_fields", type: "string" },
        { name: "encrypted_regex_pattern", type: "string" },
        { name: "encrypted_example_notification", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "bank_accounts",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "bank_name", type: "string" },
        { name: "type", type: "string" },
        { name: "encrypted_balance", type: "string" },
        { name: "encrypted_interest_rate", type: "string", isOptional: true },
        { name: "maturity_date", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "assets",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "type", type: "string" },
        { name: "purchase_date", type: "string", isOptional: true },
        { name: "encrypted_current_value", type: "string" },
        { name: "encrypted_purchase_value", type: "string" },
        { name: "encrypted_description", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
    tableSchema({
      name: "networth_snapshots",
      columns: [
        { name: "firestore_id", type: "string", isOptional: true },
        { name: "user_id", type: "string", isIndexed: true },
        { name: "date", type: "string", isIndexed: true },
        { name: "encrypted_total_bank", type: "string" },
        { name: "encrypted_total_investments", type: "string" },
        { name: "encrypted_total_assets", type: "string" },
        { name: "encrypted_total_debts", type: "string" },
        { name: "encrypted_networth", type: "string" },
        { name: "encrypted_liquid_funds", type: "string" },
        { name: "created_at", type: "number" },
        { name: "is_synced", type: "boolean" },
      ],
    }),
  ],
})
